# ===================================================================
# Spring Boot application properties
#
# For a list of common properties, check the Spring Boot docs:
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# BANNER
#banner.location=classpath:banner.txt

# LOGGING
logging:
  level:
    root: INFO
    org:
      apache: WARN
      springframework: WARN
      kurento: INFO

# OUTPUT
# Terminal color output; one of [ALWAYS, DETECT, NEVER]
spring:
  output:
    ansi:
      enabled: DETECT
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://106.54.254.212:3306/live-server?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 6162659

#      filters: stat,wall,log4j
# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION
server:
  port:
    8443

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations:
    - classpath*:mapper_**/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.kurento.tutorial.one2manycall.entity
  global-config:
    db-config:
      #    super-mapper-class: com.hengyunsoft.db.MyBaseMapper
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      db-type: MYSQL
      #驼峰下划线转换
      #      db-column-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #刷新mapper 调试神器
      #      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 4
      logic-not-delete-value: 0
  #    meta-object-handler: com.hengyunsoft.platform.config.datasource.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
